[package]
name = "x86-64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
lazy_static = "1.4.0"
raw-cpuid = "9.0"
spin = "0.9"
x86_64 = "0.14"
