[package]
name = "virtio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enumflags2 = "0.7.5"
volatile = "0.4.5"
volatile-register = "0.2.1"
