[package]
name = "virtio-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drivers = { path = "../core" }
enumflags2 = "0.7.5"
virtio = { path = "../virtio" }
