[package]
name = "snail-fs"
version = "0.1.0"
authors = ["PinYu1618 <pinyuchen658503@gmail.com>"]
edition = "2021"

[dependencies]
spin = "0.5.2"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
