//! Ref: https://github.com/torvalds/linux/include/uapi/asm-generic/errno-base.h
//! Ref: https://github.com/torvalds/linux/include/uapi/asm-generic/errno.h

pub enum Error {
    OpNotPermitted = 1,
    NoSuchFileOrDir = 2,
    NoSuchProc = 3,
    IoError = 5,
    NoSuchDevOrAddr = 6,
    ArgListTooLong = 7,
    ExecFmtError = 8,
    NoChildProc = 10,
    TryAgain = 11,
    Oom = 12,
    PermissionDenied = 13,
    BadAddress = 14,
    ResourceBusy = 16,
    FileExists = 17,
    CrossDevLink = 18,
    NoSuchDevice = 19,
    NotDirectory = 20,
    IsDirectory = 21,
    InvalidArg = 22,
    FileTableOverflow = 23,
    TooManyOpenFiles = 24,
    FileTooLarge = 27,
    NoSpaceLeftOnDevice = 28,
    DeadLockWouldOccur = 35,
    NameTooLong = 36,
    InvalidSyscallNr = 38,
}
