[package]
name = "snail-user"
version = "0.1.0"
authors = ["PinYu1618 <pinyuchen658503@gmail.com>"]
edition = "2021"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
bitflags = "1.2.1"
buddy_system_allocator = "0.6"
